#! /bin/sh
### BEGIN INIT INFO
# Provides:          scrapyd
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $network $local_fs $remote_fs $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init-Script for scrapyd deamon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# vars
SCRAPY_HOME=/etc/scrapyd
SCRAPY_PID=/var/run/scrapyd.id
SCRAPY_LOGDIR=/var/lib/scrapyd/logs 

# scrapy pythonpath
export PYTHONPATH=/home/webapp/lib:/home/webapp/modules

# always run
cd $SCRAPY_HOME

# get pid
PID=0
if [ -e $SCRAPY_PID ]; then
    PID=`cat $SCRAPY_PID`
    if [ "x" = "x$PID" ]; then
        PID=0
    fi
fi

case "$1" in
  start)
      if [ 0 -ne $PID ]; then
          running=`ps --pid $PID | grep $PID`
          if [ $running ]; then
              echo "scrapyd is already running"
              exit 1
          fi
          rm $SCRAPY_PID
          PID=0
      fi
      twistd -y scrapyd.tac --pidfile $SCRAPY_PID --uid 1001 --gid 1001 \
          -l $SCRAPY_LOGDIR/scrapyd.log >$SCRAPY_LOGDIR/scrapyd.out 2>$SCRAPY_LOGDIR/scrapyd.err
      ;;
  stop)
      if [ 0 -eq $PID ]; then
          echo "scrapyd was not running"
          exit 1
      fi
      if ! kill $PID > /dev/null 2>&1; then
          tries=""
          while [ -e $SCRAPY_PID ]; do
              if [ "x$tries" = "x.........." ]; then
                  break
              fi
              sleep 2
              tries=".$tries"
              print $tries
          done
          if [ -e $SCRAPY_PID ]; then
              echo "scrapyd did not go gentle into that good night, murdering"
              kill -9 $PID
              rm SCRAPY_PID
          fi
      else
        rm $SCRAPY_PID
      fi
      ;;
  rotate-logs)
      if [ 0 -eq $PID ]; then
          echo "scrapyd was not running"
      fi
      kill -USR1 $PID
      ;;
  status)
      if [ -f "$SCRAPY_PID" ]; then
          echo "scrapyd is running"
      else
          echo "scrapyd is not running"
      fi
    ;;
  *)
      echo "Usage: /etc/init.d/scrapyd {start|stop|rotate-logs|status}"
      exit 1
    ;;
esac

exit 0

