#! /bin/sh
### BEGIN INIT INFO
# Provides:          mount-shm
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $network $local_fs $remote_fs $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init-Script 
### END INIT INFO

case "$1" in
  start)
      umount /dev/shm
      mount /dev/shm
      ;;
  stop)
      umount /dev/shm
      ;;
  *)
      echo "Usage: /etc/init.d/mount-shm {start|stop}"
      exit 1
    ;;
esac

exit 0
