#!/bin/sh 

### BEGIN INIT INFO
# Provides:       gunicorn
# Required-Start: $local_fs $syslog
# Required-Stop:  $local_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Gunicorn processes
### END INIT INFO

USER=www-data
NAME="zaposlim_se"

RETVAL=0
CONFDIR="/etc/gunicorn"

GUNICORN_PID="/tmp/gunicorn_"$NAME".pid"
GUNICORN_RUN="gunicorn_django -c $CONFDIR/gunicorn.conf.py --pid=$GUNICORN_PID"

# python & django settings
export PYTHONPATH=/home/webapp/lib:/home/webapp/modules
export DJANGO_SETTINGS_MODULE=website.settings

# source function library
. /lib/lsb/init-functions

start()
{
    echo "Starting $NAME."
    cd $CONFDIR;
    su -c "$GUNICORN_RUN" $USER && echo "OK" || echo "failed";
}

stop()
{
    echo "Stopping $NAME"
    kill -QUIT `cat $GUNICORN_PID` && rm $GUNICORN_PID && echo "OK" || echo "failed";
}

reload()
{
    echo "Reloading $NAME:"
    if [ -f $GUNICORN_PID ]
        then kill -HUP `cat $GUNICORN_PID` && echo "OK" || echo "failed";
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        reload
        ;;
    force-reload)
        stop && start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        RETVAL=1
esac
exit $RETVAL
       